# Book settings
title: Implementing Autoencoder asset pricing model in korean stock market
author: INYEOL CHOI
copyright : "2023"
logo: 'Felab_logo2.png'

# Short description about the book
description: >-
  Asset Pricing Model에 대한 이해와 Autoencoder를 이용한 구현

execute:
  execute_notebooks           : off

# HTML-specific settings
html:
  favicon: Felab_logo.png
  use_issues_button: true
  use_repository_button: true
  home_page_in_navbar         : false

# Interact link settings
notebook_interface            : "notebook"
only_build_toc_files          : true

# Launch button settings
repository:
  url                         : https://github.com/FELAB-KHU/Asset-pricing-models-using-deep-learning-networks
  path_to_book                : "mini_book"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

bibtex_bibfiles:
  - references.bib

sphinx:
  config:
    bibtex_reference_style: author_year
    html_static_path:
     - "_static"


# LaTeX settings
latex:
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
